import { defineField, defineType } from "sanity";

export default defineType({
  name: "popularCategory",
  title: "Legnépszerűbb kategória",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Cím / felirat",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "href",
      title: "Link",
      type: "string",
      description: "Belső vagy külső hivatkozás. Választhatsz a listából vagy beírhatsz saját URL-t.",
      options: {
        layout: "dropdown",
        list: [
          { title: "Főoldal", value: "/" },
          { title: "Összes laptop", value: "/laptopok/osszes" },
          { title: "Általános laptopok", value: "/kategoria/altalanos" },
          { title: "Üzleti laptopok", value: "/kategoria/uzleti" },
          { title: "Gamer laptopok", value: "/kategoria/gamer" },
          { title: "Workstation laptopok", value: "/kategoria/workstation" },
          { title: "Érintőképernyős laptopok", value: "/kategoria/erintokepernyos" },
          { title: "Összes PC", value: "/pc-k/osszes" },
          { title: "Olcsó Gamer PC-k", value: "/pc-k/osszes?category=gamer-pc-olcso-300-alatt" },
          { title: "Középkategóriás Gamer PC-k", value: "/pc-k/osszes?category=gamer-pc-300-600" },
          { title: "Felsőkategóriás Gamer PC-k", value: "/pc-k/osszes?category=gamer-pc-600-felett" },
          { title: "Felújított Gamer PC-k", value: "/pc-k/kategoria/felujitott-gamer-pc" },
          { title: "Összes telefon", value: "/telefonok/osszes" },
          { title: "Blog", value: "/blog" },
          { title: "Kapcsolat", value: "/kapcsolat" },
          { title: "Rólunk", value: "/rolunk" },
          { title: "Miért mi", value: "/miert-mi" },
          { title: "GYIK", value: "/gyik" },
          { title: "Fizetés és szállítás", value: "/fizetes-es-szallitas" },
          { title: "Garancia", value: "/garancia" },
          { title: "Rólunk", value: "/rolunk" },
          { title: "ÁSZF", value: "/aszf" },
          { title: "Adatvédelem", value: "/adatvedelem" },
          { title: "Impresszum", value: "/impresszum" },
          { title: "Kosár", value: "/kosar" },
          { title: "Pénztár", value: "/penztar" },
          { title: "Profil", value: "/profil" },
          { title: "Bejelentkezés", value: "/bejelentkezes" },
          { title: "Regisztráció", value: "/regisztracio" },
        ],
      },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "image",
      title: "Kép (300x300 ajánlott)",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "order",
      title: "Sorrend",
      type: "number",
      description: "Kisebb szám előrébb kerül",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "href",
      media: "image",
    },
  },
});
